package(default_visibility = ["//visibility:public"])

java_library(
    name = "testing",
    srcs = glob(["**/*.java"]),
    deps = [
        "//android/guava-testlib/src/com/google/common/testing",
        "//android/guava/src/com/google/common/annotations",
        "//android/guava/src/com/google/common/base",
        "//android/guava/src/com/google/common/collect",
        "//android/guava/src/com/google/common/primitives",
        "//external:checker_framework/annotations",
        "//external:error_prone/annotations",
        "//external:junit",
    ],
)
