package(default_visibility = ["//visibility:public"])

java_library(
    name = "guava",
    exports = [
        "//guava/src/com/google/common/annotations",
        "//guava/src/com/google/common/base",
        "//guava/src/com/google/common/cache",
        "//guava/src/com/google/common/collect",
        "//guava/src/com/google/common/eventbus",
        "//guava/src/com/google/common/graph",
        "//guava/src/com/google/common/hash",
        "//guava/src/com/google/common/html",
        "//guava/src/com/google/common/io",
        "//guava/src/com/google/common/math",
        "//guava/src/com/google/common/net",
        "//guava/src/com/google/common/primitives",
        "//guava/src/com/google/common/reflect",
        "//guava/src/com/google/common/xml",
    ],
)
