package(default_visibility = ["//visibility:public"])

java_library(
    name = "net",
    srcs = glob(["*.java"]),
    deps = [
        "//android/guava/src/com/google/common/annotations",
        "//android/guava/src/com/google/common/base",
        "//android/guava/src/com/google/common/collect",
        "//android/guava/src/com/google/common/escape",
        "//android/guava/src/com/google/common/hash",
        "//android/guava/src/com/google/common/io",
        "//android/guava/src/com/google/common/primitives",
        "//android/guava/src/com/google/thirdparty/publicsuffix",
        "//external:checker_framework/annotations",
        "//external:error_prone/annotations",
        "//external:jsr305",
    ],
)
