package(default_visibility = ["//visibility:public"])

java_library(
    name = "eventbus",
    srcs = glob(["*.java"]),
    deps = [
        "//android/guava/src/com/google/common/annotations",
        "//android/guava/src/com/google/common/base",
        "//android/guava/src/com/google/common/cache",
        "//android/guava/src/com/google/common/collect",
        "//android/guava/src/com/google/common/reflect",
        "//android/guava/src/com/google/common/util/concurrent",
        "//external:checker_framework/annotations",
        "//external:error_prone/annotations",
        "//external:j2objc/annotations",
        "//external:jsr305",
    ],
)
